# Install dependencies only when needed
FROM node:lts AS deps
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Install required packages
RUN apt-get update && apt-get upgrade && apt-get -y install \
  bash \
  ca-certificates \
  clang \
  cmake \
  coreutils \
  curl \ 
  gcc \
  g++ \
  git \
  gettext \
  libavc1394-dev \
  libc-dev \
  libffi-dev \
  libpng-dev \
  libwebp-dev \
  make \
  musl \
  openssl \
  python3 \
  python3-pip \
  python3-dev \
  unzip

# Python 3 as default
RUN ln -s /usr/bin/python3 /usr/local/bin/python && \
  ln -s /usr/bin/pip3 /usr/local/bin/pip && \
  pip install --upgrade pip

# Install NumPy
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h && \
  pip install numpy

RUN pip install opencv-python

# Install OpenCV
RUN mkdir opt && cd opt && \
  git clone https://github.com/opencv/opencv.git && \
  cd ./opencv && \
  mkdir release && \
  cd release && \
  cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local .. && \
  make && \
  make install


# Rebuild the source code only when needed
FROM node:lts AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn build
RUN npx prisma db push

# If using npm comment out above and use below instead
# RUN npm run build

# Production image, copy all the files and run next
FROM node:lts AS runner
WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
